### ISSUE TITLE
Missing vendor/dniccum/phone-number/dist folder

### ISSUE THREAD

**Issue by jonsugar** [dniccum/nova-phone-number#1]
Hi Doug,

This is a nice field, thanks, but just a heads-up...

I installed your package and followed your instructions but the field did not display. The following error was in my laravel.log:

`[2018-09-27 11:15:52] local.ERROR: file_get_contents(/Users/jsugar/Documents/Projects/Work/all-seasons/vendor/dniccum/phone-number/src/../dist/js/field.js): failed to open stream: No such file or directory`

I navigated to vendor/dniccum/phone-number and saw that the dist folder was indeed missing. 

After running `yarn` followed my `yarn run dev` the dist folder was generated and everything worked fine.

**Comment by dniccum** [comment]
Thanks for the heads up. I just pushed a new release with this fix: ed7eaf0
