### ISSUE TITLE
the field show null instead of "----"

### ISSUE THREAD

**Issue by yatin13490** [dniccum/nova-phone-number#10]
Hi,

I use this package and set the field option disableValidation() to remove the field from the mandatory field list.

But now, in the list and details page the value show me "null" instead of  "----".

Can you please guide me how to set the value to "-----" instead of null
![screenshot-seasons sr-2018 11 21-16-20-46](https://user-images.githubusercontent.com/6308981/48836685-70a64180-eda9-11e8-863f-cc017d6c0ef6.png)

**Comment by dniccum** [comment]
A new bug fix was just pushed to fix the field's issue where it was actively ignoring the `->nullable()` method.

Now you can leverage the `->nullValues` method to set the null value, [see here](https://nova.laravel.com/docs/2.0/resources/fields.html#nullable-fields).

**Comment by cameronmurphy** [comment]
I am having this issue too. This was my attempt:
```php
PhoneNumber::make('Mobile')
    ->sortable()
    ->format('#### ### ###')
    ->country('AU')
    ->linkOnIndex()
    ->linkOnDetail()
    ->nullable()
    ->nullValues([null, 'null'])
    ->rules('max:12'),
```

But on index and list it still looks like this:
![image](https://user-images.githubusercontent.com/1300032/118757754-0ce52c80-b8b1-11eb-908f-fd38def3186e.png)
