### ISSUE TITLE
When phone field is blank then it should be display the proper message

### ISSUE THREAD

**Issue by yatin13490** [dniccum/nova-phone-number#11]
Hey @dniccum @batFormat ,

I used this for the mobile field, but when I try to submit the form it shows me an error of the field contains an invalid number, but I have not added any kind of number with the field.

It should display the message like, "the mobile field is required" or "the mobile field not blank".

I show your package code there is only one rule "phone", but it does not check first that is required or not.

As per my concern,
![screenshot-seasons sr-2018 11 28-17-53-19](https://user-images.githubusercontent.com/6308981/49151959-5cc58700-f337-11e8-9bad-cbcbd5516a65.png)
 you have to apply two rule on the filed:
1. required
2. phone

If I disabled the rule then no rule will be applied (required rule also be removed)

**Comment by 949mac** [comment]
To tag along, my validation message is kinda useless too :)

```
            PhoneNumber::make('Cell Phone')
                ->format('1 (###) ###-####')
                ->useMaskPlaceholder()
                ->sortable(),
```

![image](https://user-images.githubusercontent.com/23151962/49190008-67772080-f325-11e8-8c4a-bd346eb853e9.png)

Any feedback is appreciated.

**Comment by yatin13490** [comment]
@949mac 

You can overwrite the validation message from the "resources/lang/en/validation.php" file like: 
...
custom' => [
    'phone' => [
        'phone' => 'The :attribute field contains an invalid number.'
    ],
],

....

**Comment by 949mac** [comment]
Thanks @yatin13490 -- I appreciate it.

**Comment by cja-github** [comment]
I have the latest version and there is no resources/lang/ directory

**Comment by dniccum** [comment]
@cja-github if you look at the [Laravel Phone](https://github.com/Propaganistas/Laravel-Phone#laravel) documentation, you can see there on how to update the error copy. This package relies directly package to render content.
