### ISSUE TITLE
[request]: add option removeMaskOnSubmit()

### ISSUE THREAD

**Issue by abordage** [dniccum/nova-phone-number#12]
Hi, Doug. Thanks for this package.

Would be great if there was an option 'remove the mask before submitting the form'

**Comment by dniccum** [comment]
Unfortunately there isn't an event listener that I can tap into to remove the masked input at this point in time within Nova. The copy that is in the input upon submission is what Nova sends to the database.

If this is deal breaker for you, you could leverage an Observer to clean up the input upon updating the model.
