### ISSUE TITLE
Does not respect nullable

### ISSUE THREAD

**Issue by ethanclevenger91** [dniccum/nova-phone-number#13]
According to [issues on the validation dependency](https://github.com/Propaganistas/Laravel-Phone/issues/93), to accept an empty field, `nullable` needs to be set in the validation rules. I assume Nova is doing this under the hood for any registered fields that have "nullable()" called on them, but this field doesn't seem to be inheriting that functionality. So:

```
PhoneNumber::make('Phone', 'contact_phone')
    ->nullable(),
```

Does not allow the form to be submitted with an empty field.

**Comment by dniccum** [comment]
I just pushed a [new release](https://github.com/dniccum/nova-phone-number/releases/tag/v1.0.6). Let me know if this doesn't work for you.

**Comment by dniccum** [comment]
I discovered a new bug, so be sure to use [version 1.0.6.1](https://github.com/dniccum/nova-phone-number/tree/v1.0.6.1) instead of the release mentioned above.

**Comment by ethanclevenger91** [comment]
@dniccum Looking at your commit, that looks to do about the same thing I ended up doing with a workaround:

```
PhoneNumber::make('Phone', 'contact_phone')
    ->rules('nullable'),
```

I'll update and verify that the more streamlined support your update introduces works as expected.
