### ISSUE TITLE
Error when trying to use the country() validator

### ISSUE THREAD

**Issue by julianpoma** [dniccum/nova-phone-number#2]
Hi! Thanks for this awesome package!

I am having the following error message when using the `->country()` validation

![image](https://user-images.githubusercontent.com/19490445/46290383-1388cf00-c562-11e8-8cd6-386b6c680930.png)

This is my code

```php
PhoneNumber::make('Phone')->country('AR'),
```

At first, I thought this was due my seeds having invalid phone numbers. I re-seed my db with a valid one for Argentina: `011 57788785` but it's still not working. I check if the formats are valid for the package in the following [demo](https://laravel-phone.herokuapp.com/)

I also tryed with other countries, like 'CA', and still no luck.

If i don't use the `->country()` validation, I don't get the error and the field shows just fine
I am using v1.0.1

Thanks in advance!

**Comment by julianpoma** [comment]
Thanks! it's solved now!

**Comment by julianpoma** [comment]
I reopen the issue because the country validation seems to not be working.

I checked the source code, and in theory, when you specify a country(), it should append the phone:AR rule to the fields validation rules. But this seems to not be working

See this example

*With the rule `phone:AR` added manually*

```
PhoneNumber::make('Phone')
                ->rules('required', 'phone:AR'),
```

![image](https://user-images.githubusercontent.com/19490445/46294854-1ccb6900-c56d-11e8-8615-51d686d1cf2e.png)

___

*With `->country('AR')`*

```
PhoneNumber::make('Phone')
                ->country('AR')
                ->rules('required'),
```

![image](https://user-images.githubusercontent.com/19490445/46294975-62883180-c56d-11e8-81e9-85e0056ce87d.png)

The field is updated and saved, even when it's an invalid number

**Comment by dniccum** [comment]
Yes you are correct, the validation appears to not being applied correctly. I will take a closer look at this item this afternoon and I will get back to you. Apologies for the delay.

**Comment by dniccum** [comment]
@julianpoma I just pushed a new release. Perform a `composer update` and give it a try.

**Comment by julianpoma** [comment]
@dniccum Its working like a charm. Thank you so much !!
