### ISSUE TITLE
Only format's input

### ISSUE THREAD

**Issue by johnpaulmedina** [dniccum/nova-phone-number#4]
I noticed that the format does not apply on the index or detail view? Is this correct behavior?

**Comment by dniccum** [comment]
I did some testing on my end, and I was not able to replicate the issue. The input masking that is applied to the input should be saved in the database with the entered digits.

What format were you looking to implement, and could you post what your code looks like?

**Comment by dniccum** [comment]
@johnpaulmedina I believe I understand what you are referring to. In order for the formatting to take effect, the model **must** be updated/saved. The formatting is not automatically applied. Let me know if you have any other questions.

**Comment by dniccum** [comment]
Yes that is correct.

**Comment by johnpaulmedina** [comment]
Just wondering - would it not be better to not change that format? If a database is configured a certain way with certain lengths this can pose a problem. Currently nova is relatively new and as it becomes more widely adopted I believe it would pose a bigger issue. 

I would suggest that the format is not applied on setter but on a getter and input only. Leaving the database table format as is and using the format visually. What are your thoughts on this?
