### ISSUE TITLE
Issues with phone number validation.

### ISSUE THREAD

**Issue by dniccum** [dniccum/nova-phone-number#6]
I also am having the same issue but I not use disableValidation. This is my config:

PhoneNumber::make('Telefone', 'phone')
                ->sortable()
                ->format('(##) #####-####')
                ->placeholder('(00) 00000-0000')
                ->linkOnDetail()
                ->linkOnIndex(),

_Originally posted by @mvnobrega in https://github.com/dniccum/nova-phone-number/issues/5#issuecomment-431913888_

**Comment by dniccum** [comment]
Moving this to its own issue.

**Comment by dniccum** [comment]
@mvnobrega This appears to be a different phone number format that the default US phone number format. What country does this number reside in?

**Comment by mvnobrega** [comment]
This is default number format in Brazil.

**Comment by dniccum** [comment]
Closing due to lack of feedback.
